spring:
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
##    Initial schema setup and data from a .sql file
#    schema:
#      - order-schema.sql
#      - ingredient-schema.sql
#      - taco-schema.sql
#      - user-schema.sql
#    data:
#      - ingredients.sql
  security:
    user:
      name: buzz
      password: infinity

#server:
#  port: 8443
#  ssl:
#    key-store: file:///path/to/mykeys.jks # or classpath:///path/to/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: WARN
#    org.springframework.security: DEBUG # or
    org:
      springframework:
        security: DEBUG
    tacos: DEBUG

taco:
  orders:
    pageSize: 10


